CREATE TABLE IF NOT EXISTS AGENDAMENTO(
  ID_AGENDAMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DATA_HORA_AGENDAMENTO DATETIME  NOT NULL,
  ID_CLIENTE INT NOT NULL,
  ID_SERVICO INT NOT NULL,
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
  FOREIGN KEY (ID_SERVICO) REFERENCES SERVICO(ID_SERVICO)
);